import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import type { Target } from '@devotta-labs/declare'
import type { LoadedConfig } from '../config-loader.ts'
import { pc, ui } from '../ui.ts'

const ENV_FILE = 'declare-env.d.ts'

export async function typegen(loaded: LoadedConfig, _args: readonly string[] = []): Promise<void> {
  await writeDeclareEnv(loaded.projectRoot, loaded.config.target)
}

export async function writeDeclareEnv(projectRoot: string, target: Target): Promise<void> {
  const outPath = resolve(projectRoot, ENV_FILE)
  const contents = render(target)

  const existing = await readIfExists(outPath)
  if (existing === contents) return

  await writeFile(outPath, contents, 'utf8')
  ui.success(`Types generated for DHIS2 ${pc.bold(target)} ${pc.dim(`(${ENV_FILE})`)}`)
}

function render(target: string): string {
  return [
    '// Auto-generated by declare-cli; do not edit.',
    '',
    "import '@devotta-labs/declare'",
    '',
    "declare module '@devotta-labs/declare' {",
    `  interface ConfiguredTargets { '${target}': true }`,
    '}',
    '',
  ].join('\n')
}

async function readIfExists(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8')
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null
    throw err
  }
}
